### ISSUE TITLE
Fix Travis CD

### ISSUE THREAD

**Issue by eshadatta-crossref** [ror-community/ror-api#121] opened 2020-10-21 11:55 UTC
Currently, the workflow is to release the master branch as a tagged version. The travis file should, in theory, detect that and deploy the new code to production. This does not happen and currently we have to manually change the tag number in the deployment repo. This should get fixed to reduce toil and promote a more seamless deployment to production.

**Comment by mariagould** [comment] 2020-12-03 00:39
Is this a duplicate of or companion to #90 ?

**Comment by eshadatta-crossref** [comment] 2020-12-03 17:26
@mariagould , no, #90 is the cloudfront invalidation stuff, it's different from this. This is to fix the travis file to fix continuous deployment.

**Closed** 2020-12-18 19:54 UTC
Labels: infrastructure
